language: python
python:
    - "3.6"

before_install:
    - "pip install pytest pytest-cov"
    - "pip install coveralls"

install:
    - "pip install -r requirements.txt"
    - "pip install ."
script:
    - "coverage run --source=stylo setup.py test"
    - "cd docs ; make doctest"

after_success:
    - "coveralls"
